export const en = {
  title: 'Remove Background',
  subtitle: 'Paste an image URL or pick a photo to start',
  urlInputPlaceholder: 'https://example.com/photo.jpg',
  pasteButton: 'Paste',
  startButton: 'Start',
  orDivider: 'OR',
  fromAlbum: 'Pick from Album',
  fromAlbumHint: 'Tap to choose an image',
  back: 'Back',
  originalLabel: 'Original',
  processingLabel: 'Processing',
  removeButton: 'Remove Background',
  phaseDetect: 'Detecting subject',
  phaseSeparate: 'Separating background',
  phaseRefine: 'Refining edges',
  phaseFinishing: 'Finishing up',
  processingHint: 'Running high-precision model on your image',
  modelHint: 'First run downloads ~80MB model. Keep this page open.',
  doneLabel: 'Done',
  changeBg: 'CHANGE BACKGROUND',
  bgTransparent: 'Transparent',
  bgWhite: 'White',
  bgBlack: 'Black',
  bgMint: 'Mint',
  bgButter: 'Butter',
  bgSky: 'Sky',
  bgCoral: 'Coral',
  bgSeaside: 'Seaside',
  bgSunset: 'Sunset',
  saveToAlbum: 'Save to Album',
  saveSuccess: 'Saved to album',
  saveFailed: 'Failed to save',
  retry: 'Try another',
  errorInvalidUrl: 'Invalid image URL',
  errorLoadImage: 'Failed to load image',
  errorProcessing: 'Failed to remove background',
  emptyHint: 'Select or load an image to start',
  ok: 'OK'
}

export type Strings = typeof en
