import type { Strings } from './en'

export const zh: Strings = {
  title: '移除背景',
  subtitle: '粘贴图片地址，或选一张照片开始',
  urlInputPlaceholder: 'https://example.com/photo.jpg',
  pasteButton: '粘贴',
  startButton: '开始',
  orDivider: '或',
  fromAlbum: '从相册选择',
  fromAlbumHint: '点击选择一张图片',
  back: '返回',
  originalLabel: '原图',
  processingLabel: '处理中',
  removeButton: '移除背景',
  phaseDetect: '识别主体',
  phaseSeparate: '分离背景',
  phaseRefine: '精修边缘',
  phaseFinishing: '即将完成',
  processingHint: '正在以高精度模型处理你的图片',
  modelHint: '首次运行需下载约 80MB 模型，请保持页面打开。',
  doneLabel: '完成',
  changeBg: '换个背景',
  bgTransparent: '透明',
  bgWhite: '白',
  bgBlack: '黑',
  bgMint: '薄荷',
  bgButter: '奶黄',
  bgSky: '天空',
  bgCoral: '珊瑚',
  bgSeaside: '海边',
  bgSunset: '夕阳',
  saveToAlbum: '保存到相册',
  saveSuccess: '已保存到相册',
  saveFailed: '保存失败',
  retry: '重新处理',
  errorInvalidUrl: '无效的图片地址',
  errorLoadImage: '图片加载失败',
  errorProcessing: '背景去除失败',
  emptyHint: '请先选择或加载一张图片',
  ok: '好的'
}
