/**
 * 内置 SF Symbols 图标数据。
 *
 * 说明：
 * 1. 这份数据按 SF Symbols 官方分类整理，覆盖常用符号。
 * 2. 运行时会用 `UIImage.fromSFSymbol()` 校验，当前 iOS 版本不存在的符号会被自动过滤，
 *    所以即使某些名称在旧系统上不可用也不会显示为空白格。
 * 3. 想要完整的 6000+ 符号，在 App 里用「导入源文件」载入 SF Symbols.app 的
 *    symbol_categories.plist 即可覆盖这份内置数据。
 */

/** `indices` 分类靠规则生成，避免手写上千条 */
function buildIndices(): string[] {
  const out: string[] = []
  const letters = 'abcdefghijklmnopqrstuvwxyz'.split('')
  const digits = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
  const shapes = ['circle', 'circle.fill', 'square', 'square.fill']
  for (const l of letters) {
    for (const s of shapes) out.push(`${l}.${s}`)
  }
  for (const d of digits) {
    for (const s of shapes) out.push(`${d}.${s}`)
  }
  for (const s of shapes) {
    out.push(`00.${s}`, `01.${s}`, `02.${s}`, `10.${s}`, `12.${s}`, `20.${s}`, `50.${s}`)
  }
  out.push(
    'number', 'number.circle', 'number.circle.fill', 'number.square', 'number.square.fill',
    'textformat.abc', 'textformat.123', 'character', 'character.book.closed',
    'questionmark', 'questionmark.circle', 'questionmark.circle.fill',
    'questionmark.square', 'questionmark.square.fill', 'questionmark.diamond', 'questionmark.diamond.fill',
    'exclamationmark', 'exclamationmark.2', 'exclamationmark.3',
    'exclamationmark.circle', 'exclamationmark.circle.fill',
    'exclamationmark.square', 'exclamationmark.square.fill',
    'exclamationmark.triangle', 'exclamationmark.triangle.fill',
    'exclamationmark.octagon', 'exclamationmark.octagon.fill',
  )
  return out
}

export const BUILTIN_SYMBOLS: Record<string, string[]> = {
  communication: [
    'mic', 'mic.fill', 'mic.circle', 'mic.circle.fill', 'mic.square', 'mic.square.fill',
    'mic.slash', 'mic.slash.fill', 'mic.slash.circle', 'mic.slash.circle.fill', 'mic.badge.plus',
    'message', 'message.fill', 'message.circle', 'message.circle.fill',
    'message.badge', 'message.badge.filled.fill', 'message.and.waveform',
    'bubble.left', 'bubble.left.fill', 'bubble.right', 'bubble.right.fill',
    'bubble.left.and.bubble.right', 'bubble.left.and.bubble.right.fill',
    'bubble.middle.bottom', 'bubble.middle.bottom.fill', 'bubble.middle.top', 'bubble.middle.top.fill',
    'ellipsis.bubble', 'ellipsis.bubble.fill', 'exclamationmark.bubble', 'exclamationmark.bubble.fill',
    'quote.bubble', 'quote.bubble.fill', 'star.bubble', 'star.bubble.fill',
    'plus.bubble', 'plus.bubble.fill', 'checkmark.bubble', 'checkmark.bubble.fill',
    'text.bubble', 'text.bubble.fill', 'captions.bubble', 'captions.bubble.fill',
    'info.bubble', 'info.bubble.fill', 'questionmark.bubble', 'questionmark.bubble.fill',
    'rectangle.3.group.bubble.left', 'bubble.left.and.exclamationmark.bubble.right',
    'phone', 'phone.fill', 'phone.circle', 'phone.circle.fill', 'phone.badge.plus',
    'phone.connection', 'phone.down', 'phone.down.fill', 'phone.down.circle', 'phone.down.circle.fill',
    'phone.arrow.up.right', 'phone.arrow.down.left', 'phone.arrow.right',
    'teletype', 'teletype.answer', 'teletype.circle', 'teletype.circle.fill',
    'video', 'video.fill', 'video.circle', 'video.circle.fill', 'video.square', 'video.square.fill',
    'video.slash', 'video.slash.fill', 'video.badge.plus', 'video.bubble', 'video.bubble.fill',
    'envelope', 'envelope.fill', 'envelope.circle', 'envelope.circle.fill',
    'envelope.open', 'envelope.open.fill', 'envelope.badge', 'envelope.badge.fill',
    'envelope.arrow.triangle.branch', 'envelope.arrow.triangle.branch.fill',
    'mail', 'mail.fill', 'mail.stack', 'mail.stack.fill', 'mail.and.text.magnifyingglass',
    'bell', 'bell.fill', 'bell.circle', 'bell.circle.fill', 'bell.square', 'bell.square.fill',
    'bell.slash', 'bell.slash.fill', 'bell.slash.circle', 'bell.slash.circle.fill',
    'bell.badge', 'bell.badge.fill', 'bell.and.waves.left.and.right', 'bell.and.waves.left.and.right.fill',
    'megaphone', 'megaphone.fill', 'speaker.wave.2.bubble.left', 'speaker.wave.2.bubble.left.fill',
    'person.wave.2', 'person.wave.2.fill', 'recordingtape',
    'paperplane', 'paperplane.fill', 'paperplane.circle', 'paperplane.circle.fill',
    'tray', 'tray.fill', 'tray.full', 'tray.full.fill', 'tray.2', 'tray.2.fill',
    'tray.and.arrow.up', 'tray.and.arrow.up.fill', 'tray.and.arrow.down', 'tray.and.arrow.down.fill',
    'at', 'at.circle', 'at.circle.fill', 'at.badge.plus', 'at.badge.minus',
    'signature', 'waveform', 'waveform.circle', 'waveform.circle.fill', 'waveform.path',
  ],

  weather: [
    'sun.min', 'sun.min.fill', 'sun.max', 'sun.max.fill', 'sun.max.circle', 'sun.max.circle.fill',
    'sunrise', 'sunrise.fill', 'sunset', 'sunset.fill',
    'sun.and.horizon', 'sun.and.horizon.fill', 'sun.dust', 'sun.dust.fill', 'sun.haze', 'sun.haze.fill',
    'moon', 'moon.fill', 'moon.circle', 'moon.circle.fill', 'moon.zzz', 'moon.zzz.fill',
    'moon.stars', 'moon.stars.fill', 'sparkles', 'moonphase.new.moon', 'moonphase.full.moon',
    'cloud', 'cloud.fill', 'cloud.drizzle', 'cloud.drizzle.fill', 'cloud.rain', 'cloud.rain.fill',
    'cloud.heavyrain', 'cloud.heavyrain.fill', 'cloud.fog', 'cloud.fog.fill',
    'cloud.hail', 'cloud.hail.fill', 'cloud.snow', 'cloud.snow.fill', 'cloud.sleet', 'cloud.sleet.fill',
    'cloud.bolt', 'cloud.bolt.fill', 'cloud.bolt.rain', 'cloud.bolt.rain.fill',
    'cloud.sun', 'cloud.sun.fill', 'cloud.sun.rain', 'cloud.sun.rain.fill',
    'cloud.sun.bolt', 'cloud.sun.bolt.fill', 'cloud.moon', 'cloud.moon.fill',
    'cloud.moon.rain', 'cloud.moon.rain.fill', 'cloud.moon.bolt', 'cloud.moon.bolt.fill',
    'smoke', 'smoke.fill', 'wind', 'wind.snow',
    'snowflake', 'snowflake.circle', 'snowflake.circle.fill',
    'tornado', 'tropicalstorm', 'hurricane',
    'thermometer.medium', 'thermometer.low', 'thermometer.high',
    'thermometer.sun', 'thermometer.sun.fill', 'thermometer.snowflake',
    'humidity', 'humidity.fill', 'aqi.low', 'aqi.medium', 'aqi.high',
    'drop', 'drop.fill', 'drop.circle', 'drop.circle.fill', 'drop.triangle', 'drop.triangle.fill',
    'rainbow', 'water.waves', 'flame', 'flame.fill', 'flame.circle', 'flame.circle.fill',
    'bolt', 'bolt.fill', 'bolt.circle', 'bolt.circle.fill', 'bolt.slash', 'bolt.slash.fill',
    'bolt.horizontal', 'bolt.horizontal.fill', 'bolt.badge.automatic', 'bolt.badge.automatic.fill',
  ],

  maps: [
    'map', 'map.fill', 'map.circle', 'map.circle.fill', 'globe', 'globe.americas', 'globe.americas.fill',
    'globe.europe.africa', 'globe.europe.africa.fill', 'globe.asia.australia', 'globe.asia.australia.fill',
    'globe.badge.chevron.backward', 'network', 'safari', 'safari.fill',
    'location', 'location.fill', 'location.circle', 'location.circle.fill',
    'location.square', 'location.square.fill', 'location.slash', 'location.slash.fill',
    'location.north', 'location.north.fill', 'location.north.line', 'location.north.line.fill',
    'location.north.circle', 'location.north.circle.fill', 'location.magnifyingglass',
    'mappin', 'mappin.circle', 'mappin.circle.fill', 'mappin.square', 'mappin.square.fill',
    'mappin.slash', 'mappin.slash.circle', 'mappin.and.ellipse',
    'pin', 'pin.fill', 'pin.circle', 'pin.circle.fill', 'pin.slash', 'pin.slash.fill',
    'signpost.left', 'signpost.left.fill', 'signpost.right', 'signpost.right.fill',
    'signpost.right.and.left', 'signpost.right.and.left.fill',
    'building.2', 'building.2.fill', 'building.2.crop.circle', 'building.2.crop.circle.fill',
    'building', 'building.fill', 'building.columns', 'building.columns.fill',
    'house.and.flag', 'house.and.flag.fill', 'house.lodge', 'house.lodge.fill',
    'road.lanes', 'road.lane.arrowtriangle.2.inward',
    'point.topleft.down.curvedto.point.bottomright.up',
    'arrow.triangle.turn.up.right.diamond', 'arrow.triangle.turn.up.right.diamond.fill',
    'arrow.triangle.turn.up.right.circle', 'arrow.triangle.turn.up.right.circle.fill',
    'arrow.triangle.swap', 'arrow.triangle.branch', 'arrow.triangle.pull',
    'compass.drawing', 'binoculars', 'binoculars.fill',
    'flag', 'flag.fill', 'flag.circle', 'flag.circle.fill', 'flag.square', 'flag.square.fill',
    'flag.slash', 'flag.slash.fill', 'flag.checkered', 'flag.2.crossed', 'flag.2.crossed.fill',
    'ferry', 'ferry.fill', 'fuelpump', 'fuelpump.fill', 'fuelpump.circle', 'fuelpump.circle.fill',
    'parkingsign', 'parkingsign.circle', 'parkingsign.circle.fill',
    'mountain.2', 'mountain.2.fill', 'beach.umbrella', 'beach.umbrella.fill',
    'tent', 'tent.fill', 'tent.2', 'tent.2.fill',
  ],

  objectsandtools: [
    'pencil', 'pencil.circle', 'pencil.circle.fill', 'pencil.slash',
    'pencil.and.outline', 'pencil.tip', 'pencil.tip.crop.circle',
    'pencil.tip.crop.circle.badge.plus', 'pencil.tip.crop.circle.badge.minus',
    'eraser', 'eraser.fill', 'eraser.line.dashed', 'eraser.line.dashed.fill',
    'square.and.pencil', 'rectangle.and.pencil.and.ellipsis',
    'scribble', 'scribble.variable', 'highlighter', 'pencil.and.ruler', 'pencil.and.ruler.fill',
    'lasso', 'lasso.badge.sparkles', 'trash', 'trash.fill', 'trash.circle', 'trash.circle.fill',
    'trash.square', 'trash.square.fill', 'trash.slash', 'trash.slash.fill',
    'folder', 'folder.fill', 'folder.circle', 'folder.circle.fill',
    'folder.badge.plus', 'folder.fill.badge.plus', 'folder.badge.minus', 'folder.fill.badge.minus',
    'folder.badge.person.crop', 'folder.badge.questionmark', 'folder.badge.gearshape',
    'paperplane.circle', 'tray.full', 'externaldrive', 'externaldrive.fill',
    'externaldrive.badge.plus', 'externaldrive.badge.checkmark', 'externaldrive.connected.to.line.below',
    'internaldrive', 'internaldrive.fill', 'opticaldiscdrive', 'opticaldiscdrive.fill',
    'archivebox', 'archivebox.fill', 'archivebox.circle', 'archivebox.circle.fill',
    'doc', 'doc.fill', 'doc.circle', 'doc.circle.fill', 'doc.badge.plus', 'doc.fill.badge.plus',
    'doc.badge.gearshape', 'doc.badge.ellipsis', 'doc.badge.arrow.up', 'doc.badge.clock',
    'doc.on.doc', 'doc.on.doc.fill', 'doc.on.clipboard', 'doc.on.clipboard.fill',
    'doc.richtext', 'doc.plaintext', 'doc.plaintext.fill', 'doc.append', 'doc.text.below.ecg',
    'doc.text', 'doc.text.fill', 'doc.text.magnifyingglass', 'doc.text.image',
    'doc.zipper', 'doc.viewfinder', 'doc.viewfinder.fill', 'doc.questionmark', 'doc.text.viewfinder',
    'clipboard', 'clipboard.fill', 'list.clipboard', 'list.clipboard.fill',
    'note', 'note.text', 'note.text.badge.plus',
    'calendar', 'calendar.circle', 'calendar.circle.fill', 'calendar.badge.plus',
    'calendar.badge.minus', 'calendar.badge.clock', 'calendar.badge.exclamationmark',
    'calendar.day.timeline.left', 'calendar.day.timeline.right',
    'book', 'book.fill', 'book.circle', 'book.circle.fill', 'book.closed', 'book.closed.fill',
    'books.vertical', 'books.vertical.fill', 'text.book.closed', 'text.book.closed.fill',
    'menucard', 'menucard.fill', 'greetingcard', 'greetingcard.fill',
    'magazine', 'magazine.fill', 'newspaper', 'newspaper.fill', 'newspaper.circle', 'newspaper.circle.fill',
    'bookmark', 'bookmark.fill', 'bookmark.circle', 'bookmark.circle.fill',
    'bookmark.square', 'bookmark.square.fill', 'bookmark.slash', 'bookmark.slash.fill',
    'graduationcap', 'graduationcap.fill', 'graduationcap.circle', 'graduationcap.circle.fill',
    'ticket', 'ticket.fill', 'paperclip', 'paperclip.circle', 'paperclip.circle.fill',
    'paperclip.badge.ellipsis', 'link', 'link.circle', 'link.circle.fill', 'link.badge.plus',
    'personalhotspot', 'gift', 'gift.fill', 'gift.circle', 'gift.circle.fill',
    'shippingbox', 'shippingbox.fill', 'shippingbox.circle', 'shippingbox.circle.fill',
    'suitcase', 'suitcase.fill', 'suitcase.cart', 'suitcase.cart.fill',
    'backpack', 'backpack.fill', 'case', 'case.fill', 'latch.2.case', 'latch.2.case.fill',
    'crown', 'crown.fill', 'sportscourt', 'sportscourt.fill',
    'hammer', 'hammer.fill', 'hammer.circle', 'hammer.circle.fill',
    'screwdriver', 'screwdriver.fill', 'wrench', 'wrench.fill',
    'wrench.adjustable', 'wrench.adjustable.fill', 'wrench.and.screwdriver', 'wrench.and.screwdriver.fill',
    'scissors', 'scissors.circle', 'scissors.circle.fill', 'scissors.badge.ellipsis',
    'eyedropper', 'eyedropper.halffull', 'eyedropper.full',
    'paintbrush', 'paintbrush.fill', 'paintbrush.pointed', 'paintbrush.pointed.fill',
    'paintpalette', 'paintpalette.fill', 'bandage', 'bandage.fill',
    'ruler', 'ruler.fill', 'level', 'level.fill',
    'gear', 'gearshape', 'gearshape.fill', 'gearshape.circle', 'gearshape.circle.fill',
    'gearshape.2', 'gearshape.2.fill', 'gear.badge.checkmark', 'gear.badge.xmark',
    'scalemass', 'scalemass.fill', 'gyroscope', 'circles.hexagongrid', 'circles.hexagongrid.fill',
    'key', 'key.fill', 'key.horizontal', 'key.horizontal.fill', 'key.viewfinder',
    'wallet.pass', 'wallet.pass.fill', 'creditcard', 'creditcard.fill',
    'cube', 'cube.fill', 'cube.transparent', 'cube.transparent.fill', 'shippingbox.and.arrow.backward',
    'cone', 'cone.fill', 'pyramid', 'pyramid.fill', 'square.stack.3d.up', 'square.stack.3d.up.fill',
    'square.2.layers.3d', 'square.3.layers.3d', 'cylinder', 'cylinder.fill',
    'lightbulb', 'lightbulb.fill', 'lightbulb.circle', 'lightbulb.circle.fill',
    'lightbulb.slash', 'lightbulb.slash.fill', 'lamp.desk', 'lamp.desk.fill',
    'powerplug', 'powerplug.fill', 'battery.100', 'battery.75', 'battery.50', 'battery.25',
    'battery.0', 'battery.100.bolt', 'bolt.batteryblock', 'bolt.batteryblock.fill',
    'flashlight.off.fill', 'flashlight.on.fill', 'camera.filters',
    'umbrella', 'umbrella.fill', 'clock', 'clock.fill', 'alarm', 'alarm.fill',
    'stopwatch', 'stopwatch.fill', 'timer', 'hourglass', 'hourglass.bottomhalf.filled',
    'trophy', 'trophy.fill', 'trophy.circle', 'trophy.circle.fill',
    'medal', 'medal.fill', 'rosette', 'checkmark.seal', 'checkmark.seal.fill',
    'seal', 'seal.fill', 'xmark.seal', 'xmark.seal.fill',
    'shield', 'shield.fill', 'shield.lefthalf.filled', 'shield.slash', 'shield.slash.fill',
    'cup.and.saucer', 'cup.and.saucer.fill', 'mug', 'mug.fill', 'takeoutbag.and.cup.and.straw',
    'wineglass', 'wineglass.fill', 'birthday.cake', 'birthday.cake.fill',
    'fork.knife', 'fork.knife.circle', 'fork.knife.circle.fill',
    'popcorn', 'popcorn.fill', 'carrot', 'carrot.fill', 'waterbottle', 'waterbottle.fill',
    'balloon', 'balloon.fill', 'balloon.2', 'balloon.2.fill', 'party.popper', 'party.popper.fill',
    'puzzlepiece', 'puzzlepiece.fill', 'puzzlepiece.extension', 'puzzlepiece.extension.fill',
    'gamecontroller', 'gamecontroller.fill', 'die.face.1', 'die.face.6',
    'atom', 'testtube.2', 'ivfluid.bag', 'syringe', 'syringe.fill',
    'pills', 'pills.fill', 'cross.vial', 'cross.vial.fill', 'facemask', 'facemask.fill',
    'trash.slash.circle', 'bag', 'bag.fill', 'bag.circle', 'bag.circle.fill',
    'bag.badge.plus', 'bag.badge.minus', 'cart', 'cart.fill', 'cart.circle', 'cart.circle.fill',
    'basket', 'basket.fill', 'giftcard', 'giftcard.fill',
    'printer', 'printer.fill', 'printer.dotmatrix', 'printer.dotmatrix.fill',
    'scanner', 'scanner.fill', 'faxmachine', 'briefcase', 'briefcase.fill',
    'briefcase.circle', 'briefcase.circle.fill', 'theatermasks', 'theatermasks.fill',
    'ticket.fill', 'megaphone.fill', 'bubbles.and.sparkles', 'bubbles.and.sparkles.fill',
  ],

  devices: [
    'iphone', 'iphone.gen1', 'iphone.gen2', 'iphone.gen3', 'iphone.slash',
    'iphone.badge.play', 'iphone.and.arrow.forward', 'iphone.radiowaves.left.and.right',
    'ipad', 'ipad.landscape', 'ipad.gen1', 'ipad.gen2', 'ipad.badge.play',
    'ipod', 'ipodtouch', 'ipodshuffle.gen4', 'applewatch', 'applewatch.watchface',
    'applewatch.radiowaves.left.and.right', 'applewatch.side.right',
    'airpods', 'airpods.gen3', 'airpodspro', 'airpodsmax', 'airpod.right', 'airpod.left',
    'homepod', 'homepod.fill', 'homepod.2', 'homepod.2.fill', 'homepodmini', 'homepodmini.fill',
    'appletv', 'appletv.fill', 'appletvremote.gen4', 'appletvremote.gen4.fill',
    'display', 'display.2', 'display.trianglebadge.exclamationmark',
    'desktopcomputer', 'desktopcomputer.and.arrow.down', 'pc', 'macpro.gen3', 'macmini', 'macmini.fill',
    'macstudio', 'macstudio.fill', 'laptopcomputer', 'laptopcomputer.and.iphone',
    'macbook', 'macbook.and.iphone', 'macwindow', 'macwindow.badge.plus', 'macwindow.on.rectangle',
    'server.rack', 'xserve', 'keyboard', 'keyboard.fill', 'keyboard.badge.ellipsis',
    'magicmouse', 'magicmouse.fill', 'computermouse', 'computermouse.fill',
    'headphones', 'headphones.circle', 'headphones.circle.fill',
    'earbuds', 'earbuds.case', 'earbuds.case.fill',
    'hifispeaker', 'hifispeaker.fill', 'hifispeaker.2', 'hifispeaker.2.fill',
    'tv', 'tv.fill', 'tv.circle', 'tv.circle.fill', 'tv.and.mediabox', 'tv.badge.wifi',
    'sensor', 'sensor.fill', 'sensor.tag.radiowaves.forward', 'sensor.tag.radiowaves.forward.fill',
    'cable.connector', 'cable.connector.horizontal', 'powercord', 'powercord.fill',
    'simcard', 'simcard.fill', 'simcard.2', 'simcard.2.fill',
    'sdcard', 'sdcard.fill', 'memorychip', 'memorychip.fill', 'cpu', 'cpu.fill',
    'watchface.applewatch.case', 'iphone.gen3.circle', 'iphone.gen3.circle.fill',
    'apple.logo', 'airtag.radiowaves.forward', 'airtag.radiowaves.forward.fill',
    'visionpro', 'visionpro.fill', 'vision.pro', 'airplayvideo', 'airplayaudio',
    'car.rear.and.tire.marks', 'candybarphone', 'flipphone', 'deskview', 'deskview.fill',
    'lifepreserver', 'lifepreserver.fill', 'binoculars.fill',
    'opticaldisc', 'opticaldisc.fill', 'radio', 'radio.fill', 'guitars', 'guitars.fill',
    'restart', 'restart.circle', 'restart.circle.fill', 'power', 'power.circle', 'power.circle.fill',
    'power.dotted', 'togglepower', 'poweron', 'poweroff', 'powersleep',
  ],

  cameraandphotos: [
    'camera', 'camera.fill', 'camera.circle', 'camera.circle.fill',
    'camera.badge.ellipsis', 'camera.fill.badge.ellipsis', 'camera.on.rectangle', 'camera.on.rectangle.fill',
    'camera.viewfinder', 'camera.metering.center.weighted', 'camera.metering.matrix',
    'camera.aperture', 'camera.shutter.button', 'camera.shutter.button.fill',
    'camera.macro', 'camera.macro.circle', 'camera.macro.circle.fill',
    'camera.rotate', 'camera.rotate.fill', 'arrow.triangle.2.circlepath.camera',
    'video.and.waveform', 'video.and.waveform.fill', 'photo', 'photo.fill',
    'photo.circle', 'photo.circle.fill', 'photo.on.rectangle', 'photo.on.rectangle.fill',
    'photo.on.rectangle.angled', 'photo.stack', 'photo.stack.fill',
    'photo.tv', 'photo.artframe', 'photo.badge.plus', 'photo.badge.plus.fill',
    'photo.badge.arrow.down', 'photo.badge.checkmark',
    'rectangle.stack', 'rectangle.stack.fill', 'rectangle.on.rectangle', 'rectangle.on.rectangle.fill',
    'square.stack', 'square.stack.fill', 'squares.below.rectangle',
    'rectangle.stack.badge.plus', 'rectangle.stack.badge.minus',
    'rectangle.stack.badge.person.crop', 'rectangle.stack.badge.person.crop.fill',
    'livephoto', 'livephoto.slash', 'livephoto.play', 'circlebadge.2', 'circlebadge.2.fill',
    'crop', 'crop.rotate', 'rotate.left', 'rotate.left.fill', 'rotate.right', 'rotate.right.fill',
    'wand.and.rays', 'wand.and.rays.inverse', 'wand.and.stars', 'wand.and.stars.inverse',
    'sparkle.magnifyingglass', 'f.cursive', 'timelapse', 'aspectratio', 'aspectratio.fill',
    'dial.low', 'dial.low.fill', 'dial.medium', 'dial.high', 'dial.high.fill',
    'flash.off.fill', 'bolt.badge.a', 'bolt.badge.a.fill',
    'circle.dotted', 'circle.grid.cross', 'circle.grid.cross.fill',
    'grid', 'grid.circle', 'grid.circle.fill', 'squareshape', 'squareshape.fill',
    'slowmo', 'timelapse', 'cameraviewfinder', 'panorama', 'panorama.fill',
    'text.viewfinder', 'person.crop.rectangle', 'person.crop.rectangle.fill',
    'face.smiling', 'face.smiling.inverse', 'face.dashed', 'face.dashed.fill',
    'eye', 'eye.fill', 'eye.circle', 'eye.circle.fill', 'eye.slash', 'eye.slash.fill',
    'eye.square', 'eye.square.fill', 'eye.trianglebadge.exclamationmark',
  ],

  gaming: [
    'gamecontroller', 'gamecontroller.fill', 'arcade.stick', 'arcade.stick.console',
    'l.joystick', 'l.joystick.fill', 'r.joystick', 'r.joystick.fill',
    'dpad', 'dpad.fill', 'dpad.up.filled', 'dpad.down.filled', 'dpad.left.filled', 'dpad.right.filled',
    'circle.circle', 'circle.circle.fill', 'square.circle', 'square.circle.fill',
    'triangle.circle', 'triangle.circle.fill', 'xmark.circle', 'xmark.circle.fill',
    'l1.rectangle.roundedbottom', 'r1.rectangle.roundedbottom',
    'l2.rectangle.roundedtop', 'r2.rectangle.roundedtop',
    'lb.rectangle.roundedbottom', 'rb.rectangle.roundedbottom',
    'zl.rectangle.roundedtop', 'zr.rectangle.roundedtop',
    'die.face.1', 'die.face.1.fill', 'die.face.2', 'die.face.2.fill',
    'die.face.3', 'die.face.3.fill', 'die.face.4', 'die.face.4.fill',
    'die.face.5', 'die.face.5.fill', 'die.face.6', 'die.face.6.fill',
    'suit.heart', 'suit.heart.fill', 'suit.club', 'suit.club.fill',
    'suit.diamond', 'suit.diamond.fill', 'suit.spade', 'suit.spade.fill',
    'trophy', 'trophy.fill', 'medal', 'medal.fill', 'flag.checkered', 'flag.checkered.2.crossed',
    'puzzlepiece', 'puzzlepiece.fill', 'formfitting.gamecontroller', 'formfitting.gamecontroller.fill',
    'playstation.logo', 'xbox.logo', 'logo.xbox',
  ],

  connectivity: [
    'wifi', 'wifi.slash', 'wifi.exclamationmark', 'wifi.circle', 'wifi.circle.fill',
    'wifi.square', 'wifi.square.fill', 'wifi.router', 'wifi.router.fill',
    'dot.radiowaves.left.and.right', 'dot.radiowaves.right', 'dot.radiowaves.forward',
    'antenna.radiowaves.left.and.right', 'antenna.radiowaves.left.and.right.slash',
    'antenna.radiowaves.left.and.right.circle', 'antenna.radiowaves.left.and.right.circle.fill',
    'cellularbars', 'chart.bar.doc.horizontal', 'network', 'network.slash', 'network.badge.shield.half.filled',
    'bonjour', 'airplayaudio', 'airplayaudio.circle', 'airplayaudio.circle.fill',
    'airplayvideo', 'airplayvideo.circle', 'airplayvideo.circle.fill',
    'airplane', 'airplane.circle', 'airplane.circle.fill', 'airplane.departure', 'airplane.arrival',
    'personalhotspot', 'personalhotspot.circle', 'personalhotspot.circle.fill',
    'point.3.connected.trianglepath.dotted', 'point.3.filled.connected.trianglepath.dotted',
    'point.topleft.down.curvedto.point.filled.bottomright.up',
    'chart.bar.xaxis', 'waveform.badge.plus', 'waveform.badge.minus',
    'badge.plus.radiowaves.right', 'badge.plus.radiowaves.forward',
    'radiowaves.left', 'radiowaves.right', 'app.connected.to.app.below.fill',
    'externaldrive.connected.to.line.below', 'externaldrive.connected.to.line.below.fill',
    'icloud', 'icloud.fill', 'icloud.circle', 'icloud.circle.fill', 'icloud.slash', 'icloud.slash.fill',
    'icloud.and.arrow.up', 'icloud.and.arrow.up.fill', 'icloud.and.arrow.down', 'icloud.and.arrow.down.fill',
    'arrow.up.arrow.down.circle', 'arrow.up.arrow.down.circle.fill',
    'arrow.triangle.2.circlepath', 'arrow.triangle.2.circlepath.circle', 'arrow.triangle.2.circlepath.circle.fill',
    'link.icloud', 'link.icloud.fill', 'lock.icloud', 'lock.icloud.fill',
    'server.rack', 'display.and.arrow.down', 'shareplay', 'shareplay.slash',
  ],

  transportation: [
    'car', 'car.fill', 'car.circle', 'car.circle.fill', 'bolt.car', 'bolt.car.fill',
    'car.2', 'car.2.fill', 'car.rear', 'car.rear.fill', 'car.front.waves.up', 'car.front.waves.up.fill',
    'car.side', 'car.side.fill', 'car.top.door.front.left.open', 'steeringwheel',
    'bus', 'bus.fill', 'bus.doubledecker', 'bus.doubledecker.fill',
    'tram', 'tram.fill', 'tram.circle', 'tram.circle.fill', 'tram.tunnel.fill',
    'cablecar', 'cablecar.fill', 'lightrail', 'lightrail.fill',
    'ferry', 'ferry.fill', 'sailboat', 'sailboat.fill', 'sailboat.circle', 'sailboat.circle.fill',
    'truck.box', 'truck.box.fill', 'truck.pickup.side', 'truck.pickup.side.fill',
    'bicycle', 'bicycle.circle', 'bicycle.circle.fill', 'scooter', 'moped', 'moped.fill',
    'motorcycle', 'motorcycle.fill', 'airplane', 'airplane.circle', 'airplane.circle.fill',
    'airplane.departure', 'airplane.arrival', 'helicopter', 'helicopter.fill',
    'fuelpump', 'fuelpump.fill', 'ev.charger', 'ev.charger.fill', 'ev.plug.ac.type.1',
    'parkingsign', 'parkingsign.circle', 'parkingsign.circle.fill',
    'road.lanes', 'road.lanes.curved.left', 'road.lanes.curved.right',
    'figure.walk', 'figure.walk.circle', 'figure.walk.circle.fill', 'figure.wave',
    'stroller', 'stroller.fill', 'wheelchair', 'wheelchair.circle', 'wheelchair.circle.fill',
    'suitcase.rolling', 'suitcase.rolling.fill', 'tortoise', 'tortoise.fill', 'hare', 'hare.fill',
    'engine.combustion', 'engine.combustion.fill', 'gauge.with.dots.needle.bottom.50percent',
    'speedometer', 'minus.plus.batteryblock', 'minus.plus.batteryblock.fill',
    'tire', 'tirepressure', 'car.side.air.circulate', 'car.side.air.fresh',
  ],

  human: [
    'person', 'person.fill', 'person.circle', 'person.circle.fill',
    'person.crop.circle', 'person.crop.circle.fill', 'person.crop.circle.badge.plus',
    'person.crop.circle.fill.badge.plus', 'person.crop.circle.badge.minus',
    'person.crop.circle.badge.checkmark', 'person.crop.circle.badge.xmark',
    'person.crop.circle.badge.questionmark', 'person.crop.circle.badge.exclamationmark',
    'person.crop.square', 'person.crop.square.fill', 'person.crop.artframe',
    'person.crop.rectangle.stack', 'person.crop.rectangle.stack.fill',
    'person.2', 'person.2.fill', 'person.2.circle', 'person.2.circle.fill',
    'person.3', 'person.3.fill', 'person.3.sequence', 'person.3.sequence.fill',
    'person.badge.plus', 'person.fill.badge.plus', 'person.badge.minus', 'person.fill.badge.minus',
    'person.badge.clock', 'person.badge.clock.fill', 'person.badge.key', 'person.badge.key.fill',
    'person.badge.shield.checkmark', 'person.fill.checkmark', 'person.fill.xmark',
    'person.fill.questionmark', 'person.fill.turn.right', 'person.fill.turn.down',
    'person.fill.viewfinder', 'person.and.arrow.left.and.arrow.right',
    'person.text.rectangle', 'person.text.rectangle.fill',
    'person.line.dotted.person', 'person.line.dotted.person.fill',
    'shared.with.you', 'shared.with.you.slash', 'rectangle.stack.person.crop',
    'figure.stand', 'figure.stand.line.dotted.figure.stand', 'figure.arms.open',
    'figure.2.arms.open', 'figure.2.and.child.holdinghands', 'figure.and.child.holdinghands',
    'figure.dress.line.vertical.figure', 'figure.wave', 'figure.wave.circle', 'figure.wave.circle.fill',
    'hand.raised', 'hand.raised.fill', 'hand.raised.circle', 'hand.raised.circle.fill',
    'hand.raised.slash', 'hand.raised.slash.fill', 'hand.raised.square', 'hand.raised.square.fill',
    'hand.thumbsup', 'hand.thumbsup.fill', 'hand.thumbsup.circle', 'hand.thumbsup.circle.fill',
    'hand.thumbsdown', 'hand.thumbsdown.fill', 'hand.thumbsdown.circle', 'hand.thumbsdown.circle.fill',
    'hand.point.up', 'hand.point.up.fill', 'hand.point.up.left', 'hand.point.up.left.fill',
    'hand.point.down', 'hand.point.down.fill', 'hand.point.left', 'hand.point.left.fill',
    'hand.point.right', 'hand.point.right.fill', 'hand.tap', 'hand.tap.fill',
    'hand.draw', 'hand.draw.fill', 'hand.wave', 'hand.wave.fill',
    'hands.clap', 'hands.clap.fill', 'hands.sparkles', 'hands.sparkles.fill',
    'eye', 'eyes', 'eyes.inverse', 'eyebrow', 'nose', 'nose.fill', 'mustache', 'mustache.fill',
    'mouth', 'mouth.fill', 'ear', 'ear.fill', 'ear.badge.checkmark', 'ear.trianglebadge.exclamationmark',
    'brain', 'brain.head.profile', 'brain.filled.head.profile',
    'face.smiling', 'face.smiling.inverse', 'theatermasks', 'theatermasks.fill',
    'accessibility', 'accessibility.fill', 'figure.roll', 'figure.roll.runningpace',
  ],

  nature: [
    'leaf', 'leaf.fill', 'leaf.circle', 'leaf.circle.fill', 'leaf.arrow.triangle.circlepath',
    'tree', 'tree.fill', 'tree.circle', 'tree.circle.fill', 'camera.macro',
    'ladybug', 'ladybug.fill', 'ant', 'ant.fill', 'ant.circle', 'ant.circle.fill',
    'hare', 'hare.fill', 'tortoise', 'tortoise.fill', 'pawprint', 'pawprint.fill',
    'pawprint.circle', 'pawprint.circle.fill', 'bird', 'bird.fill', 'fish', 'fish.fill',
    'fish.circle', 'fish.circle.fill', 'dog', 'dog.fill', 'cat', 'cat.fill',
    'lizard', 'lizard.fill', 'teddybear', 'teddybear.fill',
    'atom', 'globe.central.south.asia', 'mountain.2', 'mountain.2.fill',
    'flame', 'flame.fill', 'drop', 'drop.fill', 'snowflake', 'sun.max', 'moon',
    'sparkle', 'sparkles', 'wind', 'water.waves', 'humidity',
    'allergens', 'allergens.fill', 'microbe', 'microbe.fill', 'microbe.circle', 'microbe.circle.fill',
    'carrot', 'carrot.fill', 'apple.logo', 'laurel.leading', 'laurel.trailing',
  ],

  fitness: [
    'figure.walk', 'figure.walk.circle', 'figure.walk.circle.fill', 'figure.walk.motion',
    'figure.run', 'figure.run.circle', 'figure.run.circle.fill',
    'figure.hiking', 'figure.outdoor.cycle', 'figure.indoor.cycle',
    'figure.strengthtraining.traditional', 'figure.strengthtraining.functional',
    'figure.core.training', 'figure.cooldown', 'figure.flexibility',
    'figure.mind.and.body', 'figure.yoga', 'figure.pilates',
    'figure.pool.swim', 'figure.open.water.swim', 'figure.rower',
    'figure.elliptical', 'figure.stair.stepper', 'figure.stairs',
    'figure.jumprope', 'figure.dance', 'figure.boxing', 'figure.kickboxing',
    'figure.martial.arts', 'figure.badminton', 'figure.tennis', 'figure.table.tennis',
    'figure.basketball', 'figure.soccer', 'figure.baseball', 'figure.american.football',
    'figure.golf', 'figure.bowling', 'figure.climbing', 'figure.skiing.downhill',
    'figure.skiing.crosscountry', 'figure.snowboarding', 'figure.skating',
    'figure.surfing', 'figure.sailing', 'figure.fishing', 'figure.archery',
    'figure.equestrian.sports', 'figure.fencing', 'figure.gymnastics',
    'figure.track.and.field', 'figure.volleyball', 'figure.rugby', 'figure.cricket',
    'figure.hockey', 'figure.lacrosse', 'figure.handball', 'figure.disc.sports',
    'figure.curling', 'figure.socialdance', 'figure.play', 'figure.wrestling',
    'dumbbell', 'dumbbell.fill', 'sportscourt', 'sportscourt.fill',
    'flame.fill', 'heart.circle', 'heart.circle.fill', 'medal', 'medal.fill',
    'stopwatch', 'stopwatch.fill', 'shoeprints.fill', 'figure.walk.departure',
  ],

  health: [
    'heart', 'heart.fill', 'heart.circle', 'heart.circle.fill', 'heart.square', 'heart.square.fill',
    'heart.slash', 'heart.slash.fill', 'heart.text.square', 'heart.text.square.fill',
    'bolt.heart', 'bolt.heart.fill', 'arrow.up.heart', 'arrow.up.heart.fill',
    'arrow.down.heart', 'arrow.down.heart.fill', 'arrow.clockwise.heart', 'arrow.clockwise.heart.fill',
    'waveform.path.ecg', 'waveform.path.ecg.rectangle', 'waveform.path.ecg.rectangle.fill',
    'staroflife', 'staroflife.fill', 'staroflife.circle', 'staroflife.circle.fill',
    'cross', 'cross.fill', 'cross.circle', 'cross.circle.fill', 'cross.case', 'cross.case.fill',
    'pills', 'pills.fill', 'pills.circle', 'pills.circle.fill',
    'bandage', 'bandage.fill', 'syringe', 'syringe.fill',
    'stethoscope', 'stethoscope.circle', 'stethoscope.circle.fill',
    'lungs', 'lungs.fill', 'brain', 'brain.head.profile', 'ear', 'eye',
    'facemask', 'facemask.fill', 'medical.thermometer', 'medical.thermometer.fill',
    'bed.double', 'bed.double.fill', 'bed.double.circle', 'bed.double.circle.fill',
    'zzz', 'powersleep', 'drop.degreesign', 'drop.degreesign.fill',
    'testtube.2', 'cross.vial', 'cross.vial.fill', 'ivfluid.bag', 'ivfluid.bag.fill',
    'allergens', 'microbe', 'pill', 'pill.fill', 'pill.circle', 'pill.circle.fill',
    'chart.line.uptrend.xyaxis', 'waveform.path', 'inset.filled.circle.dashed',
  ],

  home: [
    'house', 'house.fill', 'house.circle', 'house.circle.fill',
    'lightbulb', 'lightbulb.fill', 'lightbulb.2', 'lightbulb.2.fill',
    'lamp.desk', 'lamp.desk.fill', 'lamp.table', 'lamp.table.fill',
    'lamp.floor', 'lamp.floor.fill', 'lamp.ceiling', 'lamp.ceiling.fill',
    'light.recessed', 'light.recessed.fill', 'light.panel', 'light.panel.fill',
    'light.strip.2', 'light.strip.2.fill', 'light.beacon.max', 'light.beacon.max.fill',
    'chandelier', 'chandelier.fill', 'spigot', 'spigot.fill',
    'shower', 'shower.fill', 'bathtub', 'bathtub.fill', 'toilet', 'toilet.fill',
    'sink', 'sink.fill', 'washer', 'washer.fill', 'dryer', 'dryer.fill',
    'dishwasher', 'dishwasher.fill', 'oven', 'oven.fill', 'cooktop', 'cooktop.fill',
    'microwave', 'microwave.fill', 'refrigerator', 'refrigerator.fill',
    'stove', 'stove.fill', 'sofa', 'sofa.fill', 'chair', 'chair.fill',
    'chair.lounge', 'chair.lounge.fill', 'bed.double', 'bed.double.fill',
    'table.furniture', 'table.furniture.fill', 'cabinet', 'cabinet.fill',
    'fan', 'fan.fill', 'fan.desk', 'fan.floor', 'fan.ceiling', 'fan.ceiling.fill',
    'air.conditioner.horizontal', 'air.conditioner.horizontal.fill',
    'air.conditioner.vertical', 'air.conditioner.vertical.fill',
    'air.purifier', 'air.purifier.fill', 'humidifier', 'humidifier.fill',
    'heater.vertical', 'heater.vertical.fill', 'thermometer.medium',
    'window.vertical.closed', 'window.vertical.open', 'window.ceiling', 'window.ceiling.closed',
    'blinds.horizontal.closed', 'blinds.horizontal.open',
    'blinds.vertical.closed', 'blinds.vertical.open',
    'curtains.closed', 'curtains.open', 'door.left.hand.closed', 'door.left.hand.open',
    'door.garage.closed', 'door.garage.open', 'door.sliding.left.hand.closed',
    'entry.lever.keypad', 'entry.lever.keypad.fill', 'lock.open', 'lock',
    'videoprojector', 'videoprojector.fill', 'sensor', 'sensor.fill',
    'alarm.waves.left.and.right', 'alarm.waves.left.and.right.fill',
    'smoke', 'smoke.fill', 'carbon.dioxide.cloud', 'carbon.dioxide.cloud.fill',
    'humidity', 'poweroutlet.type.b', 'poweroutlet.type.b.fill',
    'switch.programmable', 'switch.programmable.fill', 'powerplug', 'powerplug.fill',
  ],

  editing: [
    'pencil', 'pencil.circle', 'pencil.circle.fill', 'square.and.pencil',
    'highlighter', 'lasso', 'trash', 'trash.fill', 'folder', 'paperplane',
    'scissors', 'wand.and.rays', 'wand.and.stars', 'wand.and.stars.inverse',
    'crop', 'crop.rotate', 'rotate.left', 'rotate.right',
    'flip.horizontal', 'flip.horizontal.fill', 'perspective', 'skew',
    'selection.pin.in.out', 'checkerboard.rectangle',
    'slider.horizontal.3', 'slider.horizontal.below.rectangle', 'slider.vertical.3',
    'slider.horizontal.2.square', 'slider.horizontal.2.gobackward',
    'circle.lefthalf.filled', 'circle.righthalf.filled', 'circle.bottomhalf.filled',
    'circle.tophalf.filled', 'circle.hexagongrid', 'circle.hexagongrid.fill',
    'circle.grid.3x3', 'circle.grid.3x3.fill', 'circle.grid.2x2', 'circle.grid.2x2.fill',
    'drop.triangle', 'paintbrush', 'paintbrush.pointed', 'eyedropper',
    'eyedropper.halffull', 'eyedropper.full', 'paintpalette', 'paintpalette.fill',
    'square.and.arrow.up', 'square.and.arrow.up.fill', 'square.and.arrow.up.circle',
    'square.and.arrow.up.circle.fill', 'square.and.arrow.up.on.square',
    'square.and.arrow.down', 'square.and.arrow.down.fill', 'square.and.arrow.down.on.square',
    'arrow.uturn.backward', 'arrow.uturn.backward.circle', 'arrow.uturn.backward.circle.fill',
    'arrow.uturn.forward', 'arrow.uturn.forward.circle', 'arrow.uturn.forward.circle.fill',
    'arrow.counterclockwise', 'arrow.counterclockwise.circle', 'arrow.counterclockwise.circle.fill',
    'arrow.clockwise', 'arrow.clockwise.circle', 'arrow.clockwise.circle.fill',
    'plus', 'plus.circle', 'plus.circle.fill', 'plus.square', 'plus.square.fill',
    'minus', 'minus.circle', 'minus.circle.fill', 'minus.square', 'minus.square.fill',
    'checkmark', 'checkmark.circle', 'checkmark.circle.fill', 'checkmark.square', 'checkmark.square.fill',
    'xmark', 'xmark.circle', 'xmark.circle.fill', 'xmark.square', 'xmark.square.fill',
    'ellipsis', 'ellipsis.circle', 'ellipsis.circle.fill', 'ellipsis.rectangle', 'ellipsis.rectangle.fill',
    'magnifyingglass', 'magnifyingglass.circle', 'magnifyingglass.circle.fill',
    'plus.magnifyingglass', 'minus.magnifyingglass', 'text.magnifyingglass',
    'line.3.horizontal.decrease', 'line.3.horizontal.decrease.circle',
    'line.3.horizontal.decrease.circle.fill', 'arrow.up.arrow.down',
    'arrow.up.and.down.text.horizontal', 'square.on.square', 'square.on.square.dashed',
    'plus.square.on.square', 'square.filled.on.square', 'rectangle.portrait.on.rectangle.portrait',
    'square.grid.2x2', 'square.grid.2x2.fill', 'square.grid.3x3', 'square.grid.3x3.fill',
    'square.grid.3x2', 'square.grid.3x2.fill', 'rectangle.split.2x1', 'rectangle.split.3x1',
    'rectangle.split.2x2', 'rectangle.split.3x3',
    'align.horizontal.left', 'align.horizontal.center', 'align.horizontal.right',
    'align.vertical.top', 'align.vertical.center', 'align.vertical.bottom',
    'arrow.up.left.and.arrow.down.right', 'arrow.down.right.and.arrow.up.left',
    'arrow.up.backward.and.arrow.down.forward', 'arrow.down.forward.and.arrow.up.backward',
    'arrow.up.left.and.down.right.magnifyingglass', 'square.arrowtriangle.4.outward',
    'sparkles', 'sparkle', 'timeline.selection', 'dial.min', 'dial.max',
  ],

  textformatting: [
    'textformat', 'textformat.size', 'textformat.size.smaller', 'textformat.size.larger',
    'textformat.alt', 'textformat.superscript', 'textformat.subscript',
    'textformat.abc', 'textformat.abc.dottedunderline', 'textformat.123',
    'bold', 'italic', 'underline', 'strikethrough', 'shadow',
    'bold.italic.underline', 'bold.underline', 'character', 'character.cursor.ibeam',
    'a.magnify', 'textformat.12', 'text.justify', 'text.justify.left', 'text.justify.right',
    'text.alignleft', 'text.aligncenter', 'text.alignright',
    'text.append', 'text.insert', 'text.quote', 'text.badge.plus', 'text.badge.minus',
    'text.badge.checkmark', 'text.badge.xmark', 'text.badge.star',
    'list.bullet', 'list.bullet.circle', 'list.bullet.circle.fill',
    'list.bullet.indent', 'list.bullet.rectangle', 'list.bullet.rectangle.fill',
    'list.bullet.rectangle.portrait', 'list.dash', 'list.number', 'list.star',
    'list.triangle', 'list.and.film', 'list.clipboard', 'list.bullet.below.rectangle',
    'increase.indent', 'decrease.indent', 'increase.quotelevel', 'decrease.quotelevel',
    'text.line.first.and.arrowtriangle.forward', 'text.line.last.and.arrowtriangle.forward',
    'text.word.spacing', 'paragraphsign', 'signature',
    'textbox', 'text.cursor', 'text.redaction', 'character.textbox',
    'character.bubble', 'character.bubble.fill', 'character.book.closed',
    'abc', 'quote.opening', 'quote.closing',
    'text.viewfinder', 'doc.text', 'doc.richtext', 'note.text',
    'a.square', 'a.square.fill', 'textformat.size.smaller.ar', 'globe.badge.chevron.backward',
  ],

  media: [
    'play', 'play.fill', 'play.circle', 'play.circle.fill', 'play.square', 'play.square.fill',
    'play.rectangle', 'play.rectangle.fill', 'play.slash', 'play.slash.fill',
    'pause', 'pause.fill', 'pause.circle', 'pause.circle.fill', 'pause.rectangle', 'pause.rectangle.fill',
    'playpause', 'playpause.fill', 'stop', 'stop.fill', 'stop.circle', 'stop.circle.fill',
    'record.circle', 'record.circle.fill', 'backward', 'backward.fill',
    'backward.circle', 'backward.circle.fill', 'forward', 'forward.fill',
    'forward.circle', 'forward.circle.fill', 'backward.end', 'backward.end.fill',
    'forward.end', 'forward.end.fill', 'backward.end.alt', 'backward.end.alt.fill',
    'forward.end.alt', 'forward.end.alt.fill', 'backward.frame', 'backward.frame.fill',
    'forward.frame', 'forward.frame.fill', 'eject', 'eject.fill', 'eject.circle', 'eject.circle.fill',
    'goforward', 'goforward.5', 'goforward.10', 'goforward.15', 'goforward.30', 'goforward.60',
    'gobackward', 'gobackward.5', 'gobackward.10', 'gobackward.15', 'gobackward.30', 'gobackward.60',
    'shuffle', 'shuffle.circle', 'shuffle.circle.fill', 'repeat', 'repeat.1',
    'repeat.circle', 'repeat.circle.fill', 'infinity', 'infinity.circle', 'infinity.circle.fill',
    'speaker', 'speaker.fill', 'speaker.circle', 'speaker.circle.fill',
    'speaker.slash', 'speaker.slash.fill', 'speaker.slash.circle', 'speaker.slash.circle.fill',
    'speaker.zzz', 'speaker.zzz.fill', 'speaker.wave.1', 'speaker.wave.1.fill',
    'speaker.wave.2', 'speaker.wave.2.fill', 'speaker.wave.2.circle', 'speaker.wave.2.circle.fill',
    'speaker.wave.3', 'speaker.wave.3.fill', 'speaker.minus', 'speaker.plus',
    'music.note', 'music.note.list', 'music.note.house', 'music.note.house.fill',
    'music.mic', 'music.mic.circle', 'music.mic.circle.fill',
    'music.quarternote.3', 'metronome', 'metronome.fill',
    'guitars', 'guitars.fill', 'pianokeys', 'pianokeys.inverse', 'tuningfork',
    'waveform', 'waveform.circle', 'waveform.circle.fill', 'waveform.path',
    'waveform.path.badge.plus', 'waveform.path.badge.minus', 'waveform.and.mic',
    'film', 'film.fill', 'film.circle', 'film.circle.fill', 'film.stack', 'film.stack.fill',
    'movieclapper', 'movieclapper.fill', 'popcorn', 'popcorn.fill',
    'tv', 'tv.fill', 'tv.inset.filled', 'sparkles.tv', 'sparkles.tv.fill',
    'rectangle.on.rectangle.angled', 'pip', 'pip.fill', 'pip.enter', 'pip.exit',
    'rectangle.inset.filled.and.person.filled', 'rectangle.and.text.magnifyingglass',
    'captions.bubble', 'captions.bubble.fill', 'text.bubble',
    'airplayvideo', 'airplayaudio', 'volume.fill', 'volume', 'megaphone',
    'video.badge.waveform', 'video.badge.waveform.fill', 'appletvremote.gen4',
  ],

  keyboard: [
    'keyboard', 'keyboard.fill', 'keyboard.badge.ellipsis', 'keyboard.badge.ellipsis.fill',
    'keyboard.badge.eye', 'keyboard.badge.eye.fill', 'keyboard.chevron.compact.down',
    'keyboard.chevron.compact.down.fill', 'keyboard.chevron.compact.left',
    'keyboard.onehanded.left', 'keyboard.onehanded.right', 'globe', 'globe.badge.chevron.backward',
    'command', 'command.circle', 'command.circle.fill', 'command.square', 'command.square.fill',
    'option', 'control', 'shift', 'shift.fill', 'capslock', 'capslock.fill',
    'escape', 'eject', 'delete.left', 'delete.left.fill', 'delete.right', 'delete.right.fill',
    'delete.backward', 'delete.backward.fill', 'delete.forward', 'delete.forward.fill',
    'clear', 'clear.fill', 'return', 'return.left', 'return.right',
    'space', 'tab', 'arrow.turn.down.left', 'arrow.turn.down.right',
    'projective', 'alt', 'power', 'globe.central.south.asia',
    'character.cursor.ibeam', 'text.cursor', 'cursorarrow', 'cursorarrow.click',
    'cursorarrow.click.2', 'cursorarrow.rays', 'cursorarrow.motionlines',
    'cursorarrow.and.square.on.square.dashed', 'rectangle.and.hand.point.up.left',
    'dot.circle.and.hand.point.up.left.fill', 'hand.point.up.braille', 'hand.point.up.braille.fill',
    'magnifyingglass', 'mic', 'mic.fill', 'chevron.up', 'chevron.down',
    'chevron.left', 'chevron.right', 'arrowtriangle.up.fill', 'arrowtriangle.down.fill',
  ],

  commerce: [
    'signature', 'banknote', 'banknote.fill', 'creditcard', 'creditcard.fill',
    'creditcard.circle', 'creditcard.circle.fill', 'creditcard.and.123',
    'creditcard.trianglebadge.exclamationmark', 'giftcard', 'giftcard.fill',
    'wallet.pass', 'wallet.pass.fill', 'cart', 'cart.fill', 'cart.circle', 'cart.circle.fill',
    'cart.badge.plus', 'cart.fill.badge.plus', 'cart.badge.minus', 'cart.fill.badge.minus',
    'bag', 'bag.fill', 'bag.circle', 'bag.circle.fill', 'bag.badge.plus', 'bag.badge.minus',
    'basket', 'basket.fill', 'storefront', 'storefront.fill', 'building.2', 'building.columns',
    'tag', 'tag.fill', 'tag.circle', 'tag.circle.fill', 'tag.square', 'tag.square.fill',
    'tag.slash', 'tag.slash.fill', 'ticket', 'ticket.fill',
    'dollarsign', 'dollarsign.circle', 'dollarsign.circle.fill', 'dollarsign.square', 'dollarsign.square.fill',
    'centsign.circle', 'yensign.circle', 'sterlingsign.circle', 'francsign.circle',
    'eurosign', 'eurosign.circle', 'eurosign.circle.fill',
    'yensign', 'sterlingsign', 'rublesign', 'rupeesign', 'wonsign',
    'chinesesevendaysign', 'coloncurrencysign', 'bitcoinsign', 'bitcoinsign.circle',
    'chart.bar', 'chart.bar.fill', 'chart.bar.xaxis', 'chart.pie', 'chart.pie.fill',
    'chart.line.uptrend.xyaxis', 'chart.line.downtrend.xyaxis', 'chart.line.flattrend.xyaxis',
    'chart.bar.doc.horizontal', 'chart.dots.scatter', 'chart.xyaxis.line',
    'arrow.up.right', 'arrow.down.right', 'percent', 'plus.forwardslash.minus',
    'shippingbox', 'shippingbox.fill', 'truck.box', 'truck.box.fill',
    'building.2.crop.circle', 'briefcase', 'briefcase.fill',
  ],

  time: [
    'clock', 'clock.fill', 'clock.circle', 'clock.circle.fill',
    'clock.badge', 'clock.badge.fill', 'clock.badge.checkmark', 'clock.badge.checkmark.fill',
    'clock.badge.xmark', 'clock.badge.exclamationmark', 'clock.arrow.circlepath',
    'clock.arrow.2.circlepath', 'deskclock', 'deskclock.fill',
    'alarm', 'alarm.fill', 'alarm.waves.left.and.right', 'alarm.waves.left.and.right.fill',
    'stopwatch', 'stopwatch.fill', 'timer', 'timer.circle', 'timer.circle.fill',
    'timer.square', 'hourglass', 'hourglass.circle', 'hourglass.circle.fill',
    'hourglass.bottomhalf.filled', 'hourglass.tophalf.filled',
    'calendar', 'calendar.circle', 'calendar.circle.fill',
    'calendar.badge.plus', 'calendar.badge.minus', 'calendar.badge.clock',
    'calendar.badge.exclamationmark', 'calendar.badge.checkmark',
    'calendar.day.timeline.left', 'calendar.day.timeline.right', 'calendar.day.timeline.leading',
    'gauge.with.needle', 'gauge.with.dots.needle.bottom.50percent',
    'moon.zzz', 'zzz', 'sunrise', 'sunset', 'globe.desk', 'globe.desk.fill',
  ],

  privacyandsecurity: [
    'lock', 'lock.fill', 'lock.circle', 'lock.circle.fill', 'lock.square', 'lock.square.fill',
    'lock.open', 'lock.open.fill', 'lock.open.rotation', 'lock.rotation',
    'lock.badge.clock', 'lock.badge.clock.fill', 'lock.trianglebadge.exclamationmark',
    'lock.trianglebadge.exclamationmark.fill', 'lock.doc', 'lock.doc.fill',
    'lock.rectangle', 'lock.rectangle.fill', 'lock.rectangle.stack', 'lock.rectangle.on.rectangle',
    'lock.display', 'lock.desktopcomputer', 'lock.laptopcomputer', 'lock.iphone',
    'lock.icloud', 'lock.icloud.fill', 'lock.shield', 'lock.shield.fill',
    'key', 'key.fill', 'key.horizontal', 'key.horizontal.fill', 'key.viewfinder',
    'key.icloud', 'key.icloud.fill', 'key.radiowaves.forward', 'key.radiowaves.forward.fill',
    'shield', 'shield.fill', 'shield.lefthalf.filled', 'shield.righthalf.filled',
    'shield.slash', 'shield.slash.fill', 'shield.checkerboard',
    'checkmark.shield', 'checkmark.shield.fill', 'xmark.shield', 'xmark.shield.fill',
    'exclamationmark.shield', 'exclamationmark.shield.fill', 'questionmark.shield',
    'hand.raised', 'hand.raised.fill', 'hand.raised.slash', 'hand.raised.slash.fill',
    'hand.raised.square.on.square', 'eye.slash', 'eye.slash.fill', 'eye.trianglebadge.exclamationmark',
    'faceid', 'touchid', 'person.badge.key', 'person.badge.key.fill', 'person.badge.shield.checkmark',
    'network.badge.shield.half.filled', 'wifi.exclamationmark',
    'checkerboard.shield', 'rectangle.and.hand.point.up.left.filled',
    'bolt.shield', 'bolt.shield.fill', 'cross.case', 'lifepreserver',
    'exclamationmark.lock', 'exclamationmark.lock.fill', 'nosign', 'nosign.app',
  ],

  accessibility: [
    'accessibility', 'accessibility.fill', 'accessibility.badge.arrow.up.right',
    'figure.roll', 'figure.roll.runningpace', 'wheelchair', 'wheelchair.circle', 'wheelchair.circle.fill',
    'figure.walk.motion', 'figure.walk.diamond', 'figure.walk.diamond.fill',
    'hearingdevice.ear', 'hearingdevice.and.signal.meter', 'ear.and.waveform',
    'ear.badge.checkmark', 'ear.trianglebadge.exclamationmark',
    'hand.point.up.braille', 'hand.point.up.braille.fill',
    'hand.raised.fingers.spread', 'hand.raised.fingers.spread.fill',
    'eye.trianglebadge.exclamationmark', 'eyeglasses', 'cursorarrow.motionlines',
    'cursorarrow.motionlines.click', 'cursorarrow.click.badge.clock',
    'dot.circle.and.hand.point.up.left.fill', 'rectangle.and.hand.point.up.left',
    'text.magnifyingglass', 'textformat.size', 'circle.lefthalf.filled',
    'sun.max', 'moon', 'speaker.wave.3', 'captions.bubble',
    'brain.head.profile', 'brain', 'figure.stand', 'figure.stand.line.dotted.figure.stand',
  ],

  arrows: [
    'arrow.up', 'arrow.up.circle', 'arrow.up.circle.fill', 'arrow.up.square', 'arrow.up.square.fill',
    'arrow.down', 'arrow.down.circle', 'arrow.down.circle.fill', 'arrow.down.square', 'arrow.down.square.fill',
    'arrow.left', 'arrow.left.circle', 'arrow.left.circle.fill', 'arrow.left.square', 'arrow.left.square.fill',
    'arrow.right', 'arrow.right.circle', 'arrow.right.circle.fill', 'arrow.right.square', 'arrow.right.square.fill',
    'arrow.up.left', 'arrow.up.right', 'arrow.down.left', 'arrow.down.right',
    'arrow.up.left.circle', 'arrow.up.right.circle', 'arrow.down.left.circle', 'arrow.down.right.circle',
    'arrow.up.forward', 'arrow.up.backward', 'arrow.down.forward', 'arrow.down.backward',
    'arrow.up.forward.circle', 'arrow.up.forward.circle.fill',
    'arrow.up.forward.square', 'arrow.up.forward.app', 'arrow.up.forward.app.fill',
    'arrow.left.and.right', 'arrow.up.and.down', 'arrow.up.arrow.down',
    'arrow.left.arrow.right', 'arrow.left.arrow.right.circle', 'arrow.left.arrow.right.circle.fill',
    'arrow.up.to.line', 'arrow.down.to.line', 'arrow.left.to.line', 'arrow.right.to.line',
    'arrow.up.to.line.compact', 'arrow.down.to.line.compact',
    'arrow.clockwise', 'arrow.counterclockwise', 'arrow.clockwise.circle', 'arrow.counterclockwise.circle',
    'arrow.2.circlepath', 'arrow.2.circlepath.circle', 'arrow.2.circlepath.circle.fill',
    'arrow.2.squarepath', 'arrow.triangle.2.circlepath', 'arrow.triangle.capsulepath',
    'arrow.triangle.turn.up.right.diamond', 'arrow.triangle.merge', 'arrow.triangle.swap',
    'arrow.triangle.branch', 'arrow.triangle.pull',
    'arrow.uturn.up', 'arrow.uturn.down', 'arrow.uturn.left', 'arrow.uturn.right',
    'arrow.uturn.backward', 'arrow.uturn.forward',
    'arrow.turn.up.left', 'arrow.turn.up.right', 'arrow.turn.down.left', 'arrow.turn.down.right',
    'arrow.turn.left.up', 'arrow.turn.right.up', 'arrow.turn.left.down', 'arrow.turn.right.down',
    'arrow.forward', 'arrow.backward', 'arrow.forward.square', 'arrow.backward.square',
    'arrow.up.heart', 'arrow.down.doc', 'arrow.up.doc', 'arrow.down.circle.dotted',
    'arrow.up.left.and.arrow.down.right', 'arrow.down.right.and.arrow.up.left',
    'arrow.up.and.down.and.arrow.left.and.right', 'arrow.up.left.and.down.right.and.arrow.up.right.and.down.left',
    'arrowshape.left', 'arrowshape.left.fill', 'arrowshape.right', 'arrowshape.right.fill',
    'arrowshape.up', 'arrowshape.up.fill', 'arrowshape.down', 'arrowshape.down.fill',
    'arrowshape.turn.up.left', 'arrowshape.turn.up.left.fill',
    'arrowshape.turn.up.right', 'arrowshape.turn.up.right.fill',
    'arrowshape.turn.up.backward', 'arrowshape.turn.up.backward.fill',
    'arrowshape.turn.up.forward', 'arrowshape.turn.up.forward.fill',
    'arrowshape.turn.up.left.2', 'arrowshape.turn.up.left.2.fill',
    'arrowshape.bounce.right', 'arrowshape.bounce.forward', 'arrowshape.zigzag.right',
    'arrowtriangle.up', 'arrowtriangle.up.fill', 'arrowtriangle.down', 'arrowtriangle.down.fill',
    'arrowtriangle.left', 'arrowtriangle.left.fill', 'arrowtriangle.right', 'arrowtriangle.right.fill',
    'arrowtriangle.up.circle', 'arrowtriangle.up.circle.fill',
    'arrowtriangle.down.circle', 'arrowtriangle.down.circle.fill',
    'arrowtriangle.left.circle', 'arrowtriangle.right.circle',
    'chevron.up', 'chevron.down', 'chevron.left', 'chevron.right',
    'chevron.up.circle', 'chevron.up.circle.fill', 'chevron.down.circle', 'chevron.down.circle.fill',
    'chevron.left.circle', 'chevron.left.circle.fill', 'chevron.right.circle', 'chevron.right.circle.fill',
    'chevron.up.square', 'chevron.down.square', 'chevron.left.square', 'chevron.right.square',
    'chevron.left.forwardslash.chevron.right', 'chevron.compact.up', 'chevron.compact.down',
    'chevron.compact.left', 'chevron.compact.right',
    'chevron.up.chevron.down', 'chevron.left.2', 'chevron.right.2',
    'chevron.backward', 'chevron.forward', 'chevron.backward.circle', 'chevron.forward.circle',
    'chevron.backward.2', 'chevron.forward.2',
    'control', 'increase.indent', 'decrease.indent', 'square.and.arrow.up', 'square.and.arrow.down',
    'rectangle.portrait.and.arrow.right', 'rectangle.portrait.and.arrow.forward',
    'arrow.right.doc.on.clipboard', 'arrow.up.right.and.arrow.down.left.rectangle',
    'arrow.up.right.square', 'arrow.down.left.square', 'arrow.right.circle.fill',
  ],

  math: [
    'plus', 'minus', 'plusminus', 'plusminus.circle', 'plusminus.circle.fill',
    'plus.circle', 'plus.circle.fill', 'minus.circle', 'minus.circle.fill',
    'plus.square', 'plus.square.fill', 'minus.square', 'minus.square.fill',
    'plus.rectangle', 'plus.rectangle.fill', 'minus.rectangle', 'minus.rectangle.fill',
    'multiply', 'multiply.circle', 'multiply.circle.fill', 'multiply.square', 'multiply.square.fill',
    'divide', 'divide.circle', 'divide.circle.fill', 'divide.square', 'divide.square.fill',
    'equal', 'equal.circle', 'equal.circle.fill', 'equal.square', 'equal.square.fill',
    'lessthan', 'lessthan.circle', 'lessthan.circle.fill', 'lessthan.square',
    'greaterthan', 'greaterthan.circle', 'greaterthan.circle.fill', 'greaterthan.square',
    'number', 'number.circle', 'number.circle.fill', 'number.square', 'number.square.fill',
    'percent', 'plus.forwardslash.minus', 'x.squareroot', 'function',
    'sum', 'angle', 'compass.drawing', 'ruler', 'pi',
    'infinity', 'infinity.circle', 'infinity.circle.fill',
    'chart.bar', 'chart.pie', 'chart.xyaxis.line', 'point.forward.to.point.capsulepath',
    'circle.dotted', 'grid', 'square.grid.3x3', 'textformat.123',
  ],

  shapes: [
    'circle', 'circle.fill', 'circle.dotted', 'circle.dashed', 'circle.dashed.inset.filled',
    'circle.lefthalf.filled', 'circle.righthalf.filled', 'circle.tophalf.filled', 'circle.bottomhalf.filled',
    'circle.inset.filled', 'circle.slash', 'circle.slash.fill', 'circle.grid.2x2', 'circle.grid.3x3',
    'circle.hexagongrid', 'circle.hexagonpath', 'circlebadge', 'circlebadge.fill',
    'square', 'square.fill', 'square.dotted', 'square.dashed', 'square.dashed.inset.filled',
    'square.lefthalf.filled', 'square.righthalf.filled', 'square.tophalf.filled', 'square.bottomhalf.filled',
    'square.inset.filled', 'square.slash', 'square.slash.fill', 'square.on.circle', 'square.on.square',
    'square.stack', 'square.stack.fill', 'square.grid.2x2', 'square.grid.3x3',
    'squareshape', 'squareshape.fill', 'squareshape.dashed.squareshape',
    'rectangle', 'rectangle.fill', 'rectangle.dashed', 'rectangle.inset.filled',
    'rectangle.portrait', 'rectangle.portrait.fill', 'rectangle.roundedtop', 'rectangle.roundedbottom',
    'rectangle.split.2x1', 'rectangle.split.3x1', 'rectangle.split.2x2', 'rectangle.split.3x3',
    'rectangle.leadinghalf.filled', 'rectangle.trailinghalf.filled',
    'triangle', 'triangle.fill', 'triangle.inset.filled', 'triangle.lefthalf.filled', 'triangle.righthalf.filled',
    'diamond', 'diamond.fill', 'diamond.inset.filled', 'diamond.circle', 'diamond.circle.fill',
    'octagon', 'octagon.fill', 'octagon.inset.filled',
    'hexagon', 'hexagon.fill', 'hexagon.inset.filled',
    'pentagon', 'pentagon.fill', 'pentagon.inset.filled',
    'seal', 'seal.fill', 'oval', 'oval.fill', 'oval.portrait', 'oval.portrait.fill',
    'capsule', 'capsule.fill', 'capsule.portrait', 'capsule.portrait.fill',
    'star', 'star.fill', 'star.circle', 'star.circle.fill', 'star.square', 'star.square.fill',
    'star.leadinghalf.filled', 'star.slash', 'star.slash.fill', 'sparkle',
    'heart', 'heart.fill', 'heart.circle', 'heart.circle.fill',
    'shield', 'shield.fill', 'app', 'app.fill', 'app.badge', 'app.badge.fill',
    'app.dashed', 'app.gift', 'app.gift.fill',
    'cloud', 'cloud.fill', 'drop', 'drop.fill', 'flag', 'flag.fill',
    'bookmark', 'bookmark.fill', 'tag', 'tag.fill', 'burst', 'burst.fill',
    'cube', 'cube.fill', 'cone', 'cone.fill', 'pyramid', 'pyramid.fill',
    'cylinder', 'cylinder.fill', 'sphere', 'square.on.square.dashed',
  ],

  indices: buildIndices(),
}

/** 内置分类顺序（排除虚拟分类） */
export const BUILTIN_ORDER = [
  'communication', 'weather', 'maps', 'objectsandtools', 'devices',
  'cameraandphotos', 'gaming', 'connectivity', 'transportation', 'human',
  'nature', 'fitness', 'health', 'home', 'editing', 'textformatting',
  'media', 'keyboard', 'commerce', 'time', 'privacyandsecurity',
  'accessibility', 'arrows', 'indices', 'math', 'shapes',
]
